let productos =[
    {   id:1,
        nombre: "Combo Buger 1",
        precio: 542,
        type: "burger",
        img: "img/burger.png"},
    {   id:2,
        nombre: "Combo Buger 2",
        precio: 542,
        type: "burger",
        img: "img/burger.png"},
    {   id:3,
        nombre: "Combo Buger 3",
        precio: 542,
        type: "burger",
        img: "img/burger.png"},
    {   id:4,
        nombre: "Combo Buger 4",
        precio: 542,
        type: "burger",
        img: "img/burger.png"},
    {   id:5,
        nombre: "Combo Mila 1",
            precio: 542,
            type: "mila",
            img: "img/sandwich.png"},
    {   id:6,
            nombre: "Combo Mila 2",
            precio: 542,
            type: "mila",
            img: "img/sandwich.png"},
    {   id:7,
            nombre: "Combo Mila 3",
            precio: 542,
            type: "mila",
            img: "img/sandwich.png"},
    {   id:8,
        nombre: "Combo Mila 4",
        precio: 542,
        img: "img/sandwich.png"}
           
]